params: 
    kf1 : 1.11
    kf2 : 1
    k1 : 2
    k2 : 0.4
    k3 : 2
    kd1 : 0.5
    kd2 : 0.2
    kd3 : 0.5
    v1 : 0.5
    v2 : 0.5
    v3 : 0.5
    v4 : 0
    a1 : 0
    a2 : 0
    a3 : 0
    a4 : 0
    