frequency: 5
frame_id: "body"
poses:
## trun1
  - position:
      x: -31
      y: -62
      z: 0.0
    orientation:
      x: -8.82e-07
      y: -4.34e-07
      z: 0.999
      w: -0.0000448

  - position:
      x: -45.6
      y: -52.7
      z: 0.0
    orientation:
      x: -9.86e-07
      y: 2.10e-07
      z: 0.9033
      w: 0.4288


  - position:
      x: -52.2
      y: -10
      z: 0.0
    orientation:
      x: -9.86e-07
      y: 2.10e-07
      z: 0.7372
      w: 0.6756


## central 1
  - position:
      x: -52.8
      y: -10
      z: 0.0
    orientation:
      x: -4.60e-07
      y: 9.40e-07
      z: 0.709
      w: 0.704

  - position:
      x: -52.8
      y: 45
      z: 0.0
    orientation:
      x: 3.46e-07
      y: 9.60e-07
      z: 0.7100
      w: 0.7041

  - position:
      x: -52.8
      y: 56
      z: 0.0
    orientation:
      x: 3.46e-07
      y: 9.60e-07
      z: 0.7100
      w: 0.7041

  - position:
      x: -52.8
      y: 100
      z: 0.0
    orientation:
      x: 3.46e-07
      y: 9.60e-07
      z: 0.7100
      w: 0.7041

  - position:
      x: -52.9
      y: 195
      z: 0.0
    orientation:
      x: 3.46e-07
      y: 9.60e-07
      z: 0.7100
      w: 0.7041

  - position:
      x: -47
      y: 212
      z: 0.0
    orientation:
      x: 3.46e-07
      y: 9.60e-07
      z: 0.59
      w: 0.852

  - position:
      x: -42
      y: 223
      z: 0.0
    orientation:
      x: 3.46e-07
      y: 9.60e-07
      z: 0.59
      w: 0.852

## turn2

  - position:
      x: -8.4
      y: 227
      z: 0.0
    orientation:
      x: 4.60e-07
      y: 1.02e-07
      z: -0.267
      w: 0.9635

  - position:
      x: -0.5
      y: 215.23
      z: 0.0
    orientation:
      x: -3.45e-07
      y: 8.35e-07
      z: -0.58
      w: 0.810

  - position:
      x: -3.83
      y: 184.23
      z: 0.0
    orientation:
      x: -3.45e-07
      y: 8.35e-07
      z: -0.725
      w: 0.688

## turn3
  # - position:
  #     x: -6.54
  #     y: 227.95
  #     z: 0.0
  #   orientation:
  #     x: -4.05e-07
  #     y: 7.12e-07
  #     z: -0.246
  #     w: 0.9692

  - position:
      x: -4.29
      y: 153.06
      z: 0.0
    orientation:
      x: 0.002275
      y: -0.000211
      z: -0.701
      w: 0.7125

  # - position:
  #     x: -5.34
  #     y: 125.09
  #     z: 0.0
  #   orientation:
  #     x: 0.002275
  #     y: -0.000211
  #     z: -0.869
  #     w: 0.4946

  - position:
      x: -9.05
      y: 123.91
      z: 0.0
    orientation:
      x: 0.002275
      y: -0.000211
      z: -0.99
      w: 0.1180

## turn4
  - position:
      x: -44.75
      y: 122.56
      z: 0.0
    orientation:
      x: 0.002275
      y: -0.000211
      z: -0.99
      w: 0.0100

  - position:
      x: -51
      y: 118.27
      z: 0.0
    orientation:
      x: 0.002275
      y: -0.000211
      z: -0.869
      w: 0.4947

  - position:
      x: -52
      y: 110.27
      z: 0.0
    orientation:
      x: 0.002275
      y: -0.000211
      z: -0.708
      w: 0.7057