frequency: 2
frame_id: "body"
poses:
//1
  - position:
      x: -45.55
      y: -53.05
      z: 0.0
    orientation:
      x: -8.82e-07
      y: -4.34e-07
      z: 0.32746
      w: 0.94487
//2
  - position:
      x: -41.78
      y: 225.10
      z: 0.0
    orientation:
      x: -9.86e-07
      y: 2.10e-07
      z: -0.35190
      w: 0.93604
//3
  - position:
      x: -2.710
      y: 225.83
      z: 0.0
    orientation:
      x: -4.60e-07
      y: 9.40e-07
      z: -0.91707
      w: 0.39872
//4
  - position:
      x: -5.04
      y: 126.03
      z: 0.0
    orientation:
      x: 3.46e-07
      y: 9.60e-07
      z: -0.96372
      w: -0.26691
//5
  - position:
      x: -50.30
      y: 120.25
      z: 0.0
    orientation:
      x: 4.60e-07
      y: 1.02e-07
      z: -0.93542
      w: -0.35354
//6
  - position:
      x: -49.65
      y: 48.33
      z: 0.0
    orientation:
      x: -3.45e-07
      y: 8.35e-07
      z: -0.93771
      w: 0.34743
//7
  - position:
      x: -6.14
      y: 43.12
      z: 0.0
    orientation:
      x: -4.05e-07
      y: 7.12e-07
      z: -0.90751
      w: 0.42002
//8
  - position:
      x: 12.71
      y: -61.70
      z: 0.0
    orientation:
      x: 0.002275
      y: -0.000211
      z: -0.721044
      w: 0.692885
