// Generated by gencpp from file traffic_light_detector_pkg/TrafficLightState.msg
// DO NOT EDIT!


#ifndef TRAFFIC_LIGHT_DETECTOR_PKG_MESSAGE_TRAFFICLIGHTSTATE_H
#define TRAFFIC_LIGHT_DETECTOR_PKG_MESSAGE_TRAFFICLIGHTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traffic_light_detector_pkg
{
template <class ContainerAllocator>
struct TrafficLightState_
{
  typedef TrafficLightState_<ContainerAllocator> Type;

  TrafficLightState_()
    : color()  {
    }
  TrafficLightState_(const ContainerAllocator& _alloc)
    : color(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightState_

typedef ::traffic_light_detector_pkg::TrafficLightState_<std::allocator<void> > TrafficLightState;

typedef boost::shared_ptr< ::traffic_light_detector_pkg::TrafficLightState > TrafficLightStatePtr;
typedef boost::shared_ptr< ::traffic_light_detector_pkg::TrafficLightState const> TrafficLightStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator1> & lhs, const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator1> & lhs, const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traffic_light_detector_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89e44dcab627a2c43a70ae1100695caa";
  }

  static const char* value(const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89e44dcab627a2c4ULL;
  static const uint64_t static_value2 = 0x3a70ae1100695caaULL;
};

template<class ContainerAllocator>
struct DataType< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traffic_light_detector_pkg/TrafficLightState";
  }

  static const char* value(const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color\n"
;
  }

  static const char* value(const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traffic_light_detector_pkg::TrafficLightState_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAFFIC_LIGHT_DETECTOR_PKG_MESSAGE_TRAFFICLIGHTSTATE_H
